### ISSUE TITLE
Consider paying for GitPitch

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/testing-workshop-cypress#136]
Since my promotional GitPitch Pro subscription expired after 1 year, each slide deck shows a last slide asking to pay. We could transition to something else for showing slides, or just pay for the GitPitch Pro license.

**Comment by amirrustam** [comment]
The pricing is reasonable, and we should have a subscription in place before the next workshop. We could also consider something like [mdx-deck](https://github.com/jxnblk/mdx-deck) or [remark](https://github.com/gnab/remark).

I've noticed that attendees during my workshops don't look at the slides, and I've personally stopped using them during the sessions a while ago.

Does GitPitch provide any built-in analytics?

**Comment by bahmutov** [comment]
We got the team plan, if you want to add analytics @amirrustam check out https://gitpitch.com/docs/auxiliary-features/google-analytics
