### ISSUE TITLE
TDD approach in workshop tests: make them fail by default

### ISSUE THREAD

**Issue by euZebe** [cypress-io/testing-workshop-cypress#23]
@bahmutov About the discussion we add on [Full day Cypress workshop](https://github.com/cypress-io/testing-workshop-cypress/issues/22#issuecomment-454553849), here is what I would suggest so that workshop tests fail by default, which I find is a better TDD approach:
```javascript
// create a specific command for failures
Cypress.Commands.add("fail", description => {
  throw new Error(description);
});

// in .spec.js files 
it('starts with zero items (stubbed response)', () => {
  cy.fail('start Cypress network server')
  cy.fail(`stub 'GET /todos' with []
    save the stub as an alias`)

  // THEN visit the page
  cy.visit('/')

  cy.fail(`wait for the route alias
    grab its response body
    and make sure the body is an empty list`)
})
```
The trainee will be reminded step-by-step what he has to do. 
I am not sure about the multi-fail approach, which could make him think he didn't do the expected thing he just jumped to the next fail ; any remark about it ?

Tell me If you consider it's a good idea, so that I extend it to all tests and make a PR.

**Comment by amirrustam** [comment]
While I can appreciate this perspective, this will add another layer of indirection and another thing that has be explained upfront to workshop attendees. People from various skill-levels and backgrounds attend the workshops, and this I believe would add a bit of friction despite it being a somewhat trivial change.

Some people that attend are writing tests for the very first time. 
Simple comments would be the appropriate approach here.

**Comment by euZebe** [comment]
OK.
