### ISSUE TITLE
suggestion: move lesson 4 up

### ISSUE THREAD

**Issue by gonzoRay** [cypress-io/testing-workshop-cypress#55]
First off I love this repo and this DIY workshop idea. Thank you for putting this together! 

I would like to take this opportunity to make a small suggestion I think would improve the comprehension of newcomers like me. Yesterday during lessons 1-3 I was struggling to understand what was happening at first, then realized my data wasn't being reset. This issue came up because I ended up having to run the tests a few times while I experimented with the syntax. This left some tests adding data and others failing due to leftover state. I found the `cy.request('POST', '/reset')` call and then calling that in a beforeEach (just like lesson 4). Today I got to lesson 4 and I now see that you're assuming in lessons 1-3 people either won't need to run the test more than once because they input everything perfect. 

I'd like to suggest moving lesson 4 up to the front and explaining that right away. Otherwise it leaves a bad taste when you have tests failing inexplicably. Thanks for your time Gleb. I really appreciate your efforts here. I hope this ticket helps improve this workshop. 

PS: Great docs!

**Comment by bahmutov** [comment]
thanks @gonzoRay yeah, I hit the same problem and usually say - look, we have state left from previous tests, we will deal with this later. For now, I would manually clear the todos from the browser if I needed to rerun the test. But I will leave this issue open until I find a better way

**Comment by bahmutov** [comment]
@amirrustam what do you think? should we have data reset right away? Maybe add `beforeEach` into initial 3 specs? Or move the section 4 to be one of the first ones? I just hate idea of starting with data cleanup before doing UI testing. Maybe run the app in non-persistent mode?

**Comment by amirrustam** [comment]
Thanks for the feedback @gonzoRay, we appreciate it.

I've used this issue as a teachable moment in past workshops, and engage in a discussion about the importance of state upkeep during testing. And I take advantage of this to transition into lesson 4 which introduces the solution. 

I think getting failed tests while learning is useful because it gives us opportunity to discuss **"the why"**. 

As @bahmutov, suggested, it's better to prioritize UI testing over data cleanup.

**Comment by bahmutov** [comment]
I think in this case we can call attention to this failure and explain why it happens and how we will fix it in the next section
